### ISSUE TITLE
上、下按钮不应该同时熄灭

### ISSUE THREAD

**Issue by AndreLion** [tonghuashuo/Elevator#1]
假设电梯在1层，这时3层的 `上` `下` 按钮依次被按下（点亮），那么电梯到达3层是应该先熄灭 `上` 按钮，如果电梯内部没有得到指令的话，电梯门再次打开，同时熄灭 `下` 按钮
而现在的情况是， `上` `下` 按钮同时熄灭，与实际情况不符

**Comment by tonghuashuo** [comment]
错误的预期。如果到达终点楼层后，后续没有指令，应把该楼层两个方向的等都熄灭，否则第二次开门没有任何意义。

**Comment by AndreLion** [comment]
建议用任何一台电梯实际模拟一下这个use case就知道是否真的是“错误的预期”了
同 #2

**Comment by tonghuashuo** [comment]
那请问，既然是同一楼层，除去夹门、人为按开门键等情况外，第二次开门的意义何在？

**Comment by AndreLion** [comment]
你上面提到的

> 如果到达终点楼层后，后续没有指令，应把该楼层两个方向的等都熄灭

存在逻辑漏洞，不能成立。
电梯在第一次开门之前（空载的电梯内此时无人），如何就知道它会不会得到后续指令呢？如果不能知道，那就应该第一次开门对应第一个请求（熄灭 `上` 按钮），第二次开门对应第二个请求（熄灭 `下` 按钮）

**Comment by tonghuashuo** [comment]
@AndreLion 所以根据你的描述，第一次开门是为了允许乘客进入，第二次开门仅仅是为了“走流程”，并无实际意义，是这样吗？

**Comment by AndreLion** [comment]
两次开门每一次都是走流程，每一次都可能毫无意义，因为电梯在开门之前并不知道会不会有乘客进入电梯，如果有，那就是最理想的预期，但也不能排除没有（比如等电梯的乘客手误按错，或失去耐心改走楼梯）
换句话说，你的电梯模拟器只模拟了最理想的情况，而没有考虑其他“不按套路出牌”但在真实世界中确实存在的场景。（另外一个 issue #2 , 不属于此类“不按套路出牌”的场景）

**Comment by tonghuashuo** [comment]
我不知道你@AndreLion 所在城市的电梯为何会如此设计，在我过去的经历中并没有遇到过此类设计的电梯，但在我看来这种情况下的第二次开门是没有实际意义的，是不应该发生的。

乘客在任意楼层无论按上还是按下，都表示该楼层请求服务。电梯如何响应由电梯的运行状况决定。电梯每到达一个楼层，只要开门了，就表示对该楼层进行服务，关门即为服务完成，既然服务完成那就应该把该层楼的灯都灭掉，如果有后续指令则执行，否则进入待命状态。

对于你提到的“不按套路出牌”的情况，并不影响以上逻辑。手误按错的情况确实存在，并且很多，但无论你按上还是下，都表示该楼层请求服务，只要电梯开门了，那就是服务了，应该把该楼层的灯关掉，至于运行方向和你的目的地不同，你可以选择是先进去再说，还是等它返程后再进，这是人为决定，不归电梯管。至于失去耐心改走楼梯，这更是不归电梯管，你申请了服务那我就要来，不管你是人是物还是空载，服务完我就去服务下一个，哪怕是熊孩子为了好玩，电梯开门了就是不进去，也是如此。

你反复提到的另一个 Issue，我后来去研究了下，途径方向上如有相反方向的请求是否响应并没有强制规定，买家是可以自己设定相关规则的，其他诸如限层电梯、单双层电梯，也是这样的原理。因此这个我们就不再讨论了，跟代码风格一样，just pick one 就好了。如果你认为有必要，可以在那个Issue下面留言，欢迎交流。
