### ISSUE TITLE
更远处的同向指令优先级最高

### ISSUE THREAD

**Issue by AndreLion** [tonghuashuo/Elevator#2]
假设此时电梯在1层，4层按下的 `Down` 按钮，然后8层也按下 `Down` 按钮
Actual Result: 电梯从1层上升到4层时开门，然后再去往8层
Expected Result: 电梯从1层上升，在4层不停，直接到8层开门，再往下走，到4层开门

**Comment by tonghuashuo** [comment]
错误的预期。同一方向的行进遵循“就近原则”，经过4层时应该开门，然后再到8层。
